language: java
jdk: openjdk10

before_install:
  - ./travis_release.sh

deploy:
  provider: releases
  api_key:
    secure: gfsOrvVLPFkDORrfTPoc97YRI3EJ3EdxpAPioqpSu++FvkW0hzbAGam4Tm5Sb9dVVSjWHvTrhDU49ASj6yiA17ZytcmFdXzgGxty6SB2ek8J3qtfStKP9tgXylWB1hwtMOQ55GD8GGotTrrRugeUJVOJVuwbyhFgllE7vvbS/qwNghePKUlz/QrlTH1n9n58cpAydzkx+lO+qQ0iR77c+sJMGdmqM95uckhyfOjtgyNjKd/9KKpSe2feypb3t1w7lPnJw/wbIIlAnqp5am3jtMAGxOCuKHbrKM7nlNqmCAReIR2IQt+RBJMRecIT2WnE4UCtMHF9vl57QPFRHwnf3L7zYo5lYUE5HaROEpGr70pU9a/lOBP52dGWc/cffn3ECCiIszGCDV/bIEcL9hMLyRMok5Pro9Gu2C0XbDzPmORhDUeldMDivyWz4xe5ATT/zH8yt1so+b9VkF82TkW8VoSZmfMfG+zGxL3SZDL0eEB8vdeVQlIQRZWRM0c6Ne2zoNY+ITETbe5t0Ev4wHqRsahQtnbVzRuRCTzI1BuZAg4GfRUQXWLfGdy4XzSfovPEpCFMDIGNcOx+G4oICaDEKCSMo+Y5DQLsbM004+vyw35lQOq4W6+iSaoFIA/L3IkQbuHuv0TW4LT7HwzvtINP4ohMlKZhl4hRpJ4BFjK4gzc=
  file_glob: true
  file: build/libs/gradient-progression-*.jar
  skip_cleanup: true
  on:
    repo: gradient-mod/progression
    tags: true
    all_branches: true
