@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gradientmod.progression.capabilities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
