@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gradientmod.progression.advancements;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
